name: physics_convertions_unit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/logo/
  fonts:
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins-Italic.ttf
    - asset: assets/fonts/Poppins-Black.ttf
    - asset: assets/fonts/Poppins-BlackItalic.ttf
    - asset: assets/fonts/Poppins-Bold.ttf
    - asset: assets/fonts/Poppins-BoldItalic.ttf
    - asset: assets/fonts/Poppins-ExtraBold.ttf
    - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
    - asset: assets/fonts/Poppins-ExtraLight.ttf
    - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
    - asset: assets/fonts/Poppins-Light.ttf
    - asset: assets/fonts/Poppins-LightItalic.ttf
    - asset: assets/fonts/Poppins-Medium.ttf
    - asset: assets/fonts/Poppins-MediumItalic.ttf
    - asset: assets/fonts/Poppins-SemiBold.ttf
    - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - asset: assets/fonts/Poppins-Thin.ttf
    - asset: assets/fonts/Poppins-ThinItalic.ttf


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/logo-no-background.png
  android: true
  #ios: false
  web: true
  web_splash_fade_time_ms: 20
  android_gravity: center
  android_12:
    image: assets/logo/logo-no-background.png
    color: "#ffffff"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo-no-background.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo-no-background.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo/logo-no-background.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo-no-background.png"
